overwrite: true
hooks:
  afterAllFileWrite:
    - yarn prettier --write
    - yarn eslint --ext ts --fix
#
generates:
  schema.dgraph.graphql:
    schema:
      - ${CODELAB_DGRAPH_GRAPHQL_ENDPOINT}:
    plugins:
      - schema-ast

  libs/dgraph/src/graphql-client-dgraph.generated.ts:
    schema:
      - ${CODELAB_DGRAPH_GRAPHQL_ENDPOINT}:
    documents:
      - libs/modules/**/*.d.graphql
      - apps/web/**/*.d.graphql
      - apps/web-e2e/**/*.d.graphql
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
      - typescript-document-nodes
    config:
      documentVariableSuffix: 'Gql'
      gqlImport: '@apollo/client#gql'
      skipTypename: true
      strictScalars: true
      defaultScalarType: unknown
      withRefetchFn: true
      defaultBaseOptions:
        operationName: 'dgraph'
      scalars:
        uuid: string
        json: Record<string, any>
        jsonb: Record<string, any>
        DateTime: string
        Int64: number
        _Any: any

  libs/graphql/src/graphql-client-api.generated.ts:
    schema:
      - ${CODELAB_API_ENDPOINT}/graphql:
    documents:
      - libs/modules/**/*.api.graphql
      - apps/web/**/*.api.graphql
      - apps/web-e2e/**/*.api.graphql
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
      - typescript-document-nodes
    config:
      defaultBaseOptions:
        operationName: 'api'
      documentVariableSuffix: 'Gql'
      gqlImport: '@apollo/client#gql'
      skipTypename: true
      strictScalars: true
      defaultScalarType: unknown
      withRefetchFn: true
