overwrite: true
hooks:
  afterAllFileWrite:
    - yarn prettier --write
    - yarn eslint --ext ts --fix
generates:
  schema.graphql:
    schema:
      - ${CODELAB_HASURA_GRAPHQL_ENDPOINT}:
          headers:
            - 'x-hasura-admin-secret': '${HASURA_GRAPHQL_ADMIN_SECRET}'
    plugins:
      - schema-ast

  schema.dgraph.graphql:
    schema:
      - http://127.0.0.1:8081/graphql:
    plugins:
      - schema-ast

  # Typescript + Apollo
  libs/hasura/src/graphql-client-hasura.generated.ts:
    schema:
      - ${CODELAB_HASURA_GRAPHQL_ENDPOINT}:
          headers:
            - 'x-hasura-admin-secret': '${HASURA_GRAPHQL_ADMIN_SECRET}'
    documents:
      - libs/modules/**/*[!.d].graphql
      - apps/web/**/*[!.d].graphql
      - apps/web-e2e/**/*[!.d].graphql
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
      - typescript-document-nodes
    config:
      documentVariableSuffix: 'Gql'
      gqlImport: '@apollo/client#gql'
      skipTypename: true
      strictScalars: true
      defaultScalarType: unknown
      withRefetchFn: true
      scalars:
        uuid: string
        json: Record<string, any>
        jsonb: Record<string, any>

  libs/dgraph/src/graphql-client-dgraph.generated.ts:
    schema:
      - http://127.0.0.1:8081/graphql
    documents:
      - libs/modules/**/*.d.graphql
      - apps/web/**/*.d.graphql
      - apps/web-e2e/**/*.d.graphql
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
      - typescript-document-nodes
    config:
      documentVariableSuffix: 'Gql'
      gqlImport: '@apollo/client#gql'
      skipTypename: true
      strictScalars: true
      defaultScalarType: unknown
      withRefetchFn: true
      defaultBaseOptions:
        context:
          graphqlUri: 'http://127.0.0.1:8081/graphql'
      scalars:
        uuid: string
        json: Record<string, any>
        jsonb: Record<string, any>
        DateTime: string
        Int64: number
