overwrite: true
hooks:
  afterAllFileWrite:
    - yarn prettier --write
    - yarn eslint --ext ts --fix
schema:
  - https://codelab-ai.hasura.app/v1/graphql:
      headers:
        - 'x-hasura-admin-secret': '${HASURA_GRAPHQL_ADMIN_SECRET}'
generates:
  schema.graphql:
    plugins:
      - schema-ast

  # Typescript + Apollo
  libs/generated/src/graphql-client-hasura.generated.ts:
    documents:
      - libs/modules/**/*.hasura.graphql
      - apps/web/**/*.hasura.graphql
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
      - typescript-document-nodes
    config:
      documentVariableSuffix: 'Gql'
      gqlImport: '@apollo/client#gql'
