overwrite: true
hooks:
  afterAllFileWrite:
    - npx eslint --ext ts --fix
    - npx prettier --write
generates:
  # API Schema
  schema.graphql:
    schema:
      - http://localhost:4001/graphql
      - schema.client.graphql
    plugins:
      - schema-ast

  # Typescript + Apollo
  libs/generated/src/graphql-server.generated.ts:
    schema:
      - http://localhost:4001/graphql
      - schema.client.graphql
    documents:
      - libs/modules/**/*.graphql
      - apps/web/**/*.graphql
    plugins:
      - typescript
      - typescript-operations
      - typescript-document-nodes
      - typescript-react-apollo
    config:
      documentVariableSuffix: 'Gql'
      gqlImport: '@apollo/client#gql'

  libs/generated/src/graphql-client.generated.ts:
    schema:
      - schema.client.graphql
    plugins:
      # - typescript
      # - typescript-operations
      # - typescript-document-nodes
      # - typescript-react-apollo
      # - typescript-apollo-client-helpers
      - typescript-apollo-client-helpers
      - 'typescript-typedefs.js'
    config:
      requireKeyFields: false
      requirePoliciesForAllTypes: false
      documentVariableSuffix: 'Gql'
      gqlImport: '@apollo/client#gql'
