overwrite: true
hooks:
  afterAllFileWrite:
    - yarn prettier --write
    - yarn eslint --ext ts --fix
generates:
  schema.dgraph.graphql:
    schema:
      - ${CODELAB_DGRAPH_GRAPHQL_ENDPOINT}:
    plugins:
      - schema-ast

  # libs/hasura/src/graphql-client-hasura.generated.ts:
  #   schema:
  #     - ${CODELAB_DGRAPH_GRAPHQL_ENDPOINT}:
  #   documents:
  #     - libs/modules/**/*[!.d].graphql
  #     - apps/web/**/*[!.d].graphql
  #     - apps/web-e2e/**/*[!.d].graphql
  #   plugins:
  #     - typescript
  #     - typescript-operations
  #     - typescript-react-apollo
  #     - typescript-document-nodes
  #   config:
  #     documentVariableSuffix: 'Gql'
  #     gqlImport: '@apollo/client#gql'
  #     skipTypename: true
  #     strictScalars: true
  #     defaultScalarType: unknown
  #     withRefetchFn: true
  #     scalars:
  #       Int64: number
  #       DateTime: string
  #       uuid: string
  #       json: Record<string, any>
  #       jsonb: Record<string, any>

  libs/dgraph/src/graphql-client-dgraph.generated.ts:
    schema:
      - ${CODELAB_DGRAPH_GRAPHQL_ENDPOINT}:
    documents:
      - libs/modules/**/*.d.graphql
      - apps/web/**/*.d.graphql
      - apps/web-e2e/**/*.d.graphql
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
      - typescript-document-nodes
    config:
      documentVariableSuffix: 'Gql'
      gqlImport: '@apollo/client#gql'
      skipTypename: true
      strictScalars: true
      defaultScalarType: unknown
      withRefetchFn: true
      scalars:
        uuid: string
        json: Record<string, any>
        jsonb: Record<string, any>
        DateTime: string
        Int64: number
        _Any: any
