version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth 

  neo4j:
    image: neo4j
    restart: always
    volumes:
      - ./neo4j/data:/data
    ports:
      - 7687:7687
    command: neo4j
