apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: codelab
  # labels:
  #   app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: frontend
          # imagePullPolicy: Always
          image: codelabai/codelab:0.01
          # ENTRYPOINT in Docker
          command: ['yarn', 'start:prod:web']
          env:
            - name: WEB_PORT
              value: '8080'
            - name: NODE_ENV
              value: production
            - name: NEXT_PUBLIC_API_ORIGIN
              value: http://localhost:4000
            - name: NEXT_PUBLIC_API_PATHNAME
              value: api/v1
          ports:
            - name: http
              containerPort: 8080
          resources:
            # Running container is not allowed to pass the set limit
            limits:
              memory: 512Mi
              cpu: '0.5'
            # Used by scheduler to determine which node to place the Pod on, think of it as minimum required resource
            requests:
              memory: 256Mi
              cpu: '0.2'
