#
# A role binding grants the permissions defined in a role to a user or set of users.
#
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: codelab-role-binding
  namespace: codelab

# List of subjects (users, groups, or service accounts) for defining permissions
subjects:
  - kind: ServiceAccount
    name: codelab-role-binding
    namespace: codelab

# Reference to the role being granted
roleRef:
  kind: Role
  name: codelab-role-binding
  apiGroup: rbac.authorization.k8s.io
