apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-graph
  namespace: codelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-graph
  template:
    metadata:
      labels:
        app: api-graph
    spec:
      volumes:
        - name: env
          secret:
            defaultMode: 420
            secretName: env
      containers:
        - name: api-graph
          imagePullPolicy: Always
          image: codelabai/codelab:0.03
          command:
          - /bin/sh
          - -c
          - "cp /mnt/.env.dev /usr/local/codelab/.env.dev && yarn pm2-runtime /usr/local/codelab/dist/apps/api/graph/pm2.json"
          volumeMounts:
            - mountPath: /mnt/
              name: env
          ports:
            - name: http
              containerPort: 4004
          resources:
            # requests:
            #   memory: 256Mi
            #   cpu: '0.2'
---
apiVersion: v1
kind: Service
metadata:
  name: api-graph
  namespace: codelab
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4004
      targetPort: 4004
  selector:
    app: api-graph
