apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-graph
  namespace: codelab
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: api-graph
  template:
    metadata:
      labels:
        app: api-graph
    spec:
      serviceAccountName: codelab-service-account
      containers:
        - name: api-graph
          imagePullPolicy: Always
          image: codelabai/codelab:0.02
          ports:
            - name: http
              containerPort: 4004
---
apiVersion: v1
kind: Service
metadata:
  name: api-graph
  namespace: codelab
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4004
      targetPort: 4004
  selector:
    app: api-graph
