apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-graph
  namespace: codelab
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: api-graph
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "readonly"
        vault.hashicorp.com/auth-path: "auth/k8s-staging"
        vault.hashicorp.com/agent-inject-secret-env: "codelab-staging/.env"
        vault.hashicorp.com/agent-inject-template-env: |
          {{- with secret "codelab-staging/.env" -}}
          {{ .Data.data.data }}
          {{- end }}
      labels:
        app: api-graph
    spec:
      serviceAccountName: codelab-service-account
      containers:
        - name: api-graph
          imagePullPolicy: Always
          image: codelabai/codelab:0.03
          command:
            - /bin/sh
            - -c
            - 'ln -sf /vault/secrets/env /usr/local/codelab/.env && yarn pm2-runtime /usr/local/codelab/dist/apps/api/graph/pm2.json'
          ports:
            - name: http
              containerPort: 4004
          resources:
            # requests:
            #   memory: 256Mi
            #   cpu: '0.2'
---
apiVersion: v1
kind: Service
metadata:
  name: api-graph
  namespace: codelab
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4004
      targetPort: 4004
  selector:
    app: api-graph
