kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: codelab-role
  namespace: codelab
rules:
  - apiGroups: ['', 'apps', 'batch', 'extensions']
    resources:
      ['deployments', 'services', 'replicasets', 'pods', 'jobs', 'cronjobs']
    verbs: ['*']
