apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
  namespace: codelab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
