apiVersion: v1
kind: Namespace
metadata:
  name: codelab
  labels:
    sidecar-injector: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: codelab
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      serviceAccountName: codelab-service-account
      containers:
        - name: frontend
          imagePullPolicy: Always
          image: codelabai/codelab:0.01
          command: ['yarn', 'start:prod:web']
          env:
            - name: WEB_PORT
              value: '3000'
            - name: NODE_ENV
              value: production
            - name: NEXT_PUBLIC_API_ORIGIN
              value: http://localhost:4000
            - name: NEXT_PUBLIC_API_PATHNAME
              value: api/v1
          ports:
            - name: http
              containerPort: 3000
          resources:
            limits:
              memory: 512Mi
              cpu: '0.5'
            requests:
              memory: 256Mi
              cpu: '0.2'
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: codelab
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: web
