apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-graph
  namespace: codelab
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "readonly"
        vault.hashicorp.com/auth-path: "auth/k8s-staging"
        vault.hashicorp.com/agent-inject-secret-env: "codelab-staging/.env"
        vault.hashicorp.com/agent-inject-template-env: |
          {{- with secret "codelab-staging/.env" -}}
          {{ .Data.data.data }}
          {{- end }}
    spec:
      serviceAccountName: codelab-service-account
      containers:
        - name: api-graph
          command:
            - /bin/sh
            - -c
            - 'ln -sf /vault/secrets/env /usr/local/codelab/.env && yarn pm2-runtime /usr/local/codelab/dist/apps/api/graph/pm2.json'
