apiVersion: v1
kind: Service
metadata:
  name: codelab-app-staging
  namespace: default
  labels:
    app: codelab-app-staging
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app: codelab-app-staging