apiVersion: apps/v1
kind: Deployment
metadata:
  name: codelab-app-staging
  namespace: default
  labels:
    app: codelab-app-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codelab-app-staging
  template:
    metadata:
      labels:
        app: codelab-app-staging
    spec:
      containers:
        - name: codelab-app-staging
          image: codelabai/codelab:0.1
          ports:
            - containerPort: 80
              name: http
          resources:
            # Running container is not allowed to pass the set limit
            limits:
              memory: 512Mi
              cpu: "1"
            # Used by scheduler to determine which node to place the Pod on, think of it as minimum required resource
            requests:
              memory: 256Mi
              cpu: "0.2"