apiVersion: v1
# https://gist.github.com/petitviolet/d36f33d145d0bbf4b54eb187b79d0244
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: codelab
data:
  nginx.conf: |
    events {
    }

    http {
      upstream web {
        server 127.0.0.1:3000;
      }

      server {
        listen 80;
        root /home/codelab/app/dist/apps/web;

        location /web {
          proxy_pass http://web;
        }

        location /web/_next {
          root /home/codelab/app/dist/apps/web/.next;
        }
      }
    }
