#
# `--env-file`, a flag for docker-compose, is used for variable substitution
#
# `env_file` is used to find env to inject into container at runtime
#
version: '3.8'
services:
  # All other services derive from this
  codelab:
    build:
      context: ../
      dockerfile: ${PWD}/.docker/Dockerfile
    image: codelabai/codelab:${DOCKER_TAG_VERSION}
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
