#
# `--env-file`, a flag for docker-compose, is used for variable substitution
#
# `env_file` is used to find env to inject into docker container at runtime
#
# https://docs.docker.com/compose/environment-variables/
#
version: '3.8'
services:
  zero:
    container_name: codelab-dgraph-zero
    image: dgraph/dgraph:v21.03.0
    volumes:
      - dgraph:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080

  alpha:
    container_name: codelab-dgraph-alpha
    depends_on:
      - zero
    image: dgraph/dgraph:v21.03.0
    volumes:
      - dgraph:/dgraph
    ports:
      - 8081:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --security whitelist=0.0.0.0/0

  # E2E
  zero-test:
    container_name: codelab-dgraph-zero-test
    image: dgraph/dgraph:v21.03.0
    volumes:
      - dgraph-test:/dgraph
    ports:
      - 5082:5080
      - 6082:6080
    restart: on-failure
    command: dgraph zero --my=zero-test:5080

  alpha-test:
    container_name: codelab-dgraph-alpha-test
    depends_on:
      - zero-test
    image: dgraph/dgraph:v21.03.0
    volumes:
      - dgraph-test:/dgraph
    ports:
      - 8082:8080
      - 9082:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --security whitelist=0.0.0.0/0

volumes:
  dgraph:
    name: codelab-dgraph-volume
  dgraph-test:
    name: codelab-dgraph-test-volume
