version: '3.8'
services:
  app:
    restart: always
    ports:
      - 3333:3333
      - 4200:4200
    build:
      context: ../
#      cache_from:
#        # - codelabstudios/codelab_builder:v0.0.1
#        - node:14.11.0-alpine
      dockerfile: $PWD/.docker/Dockerfile
      args:
        - NODE_ENV=production
    image: codelabai/codelab:0.1
    # volumes:
    #   - codelab-volume:/app

  fluentd:
    ports:
      - 24224:24224
    container_name: fluentd
    image: fluentd
    tty: true # colorize output
    environment:
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor
    build:
      context: ./fluentd
    volumes:
      - ./fluentd/configs:/fluentd/etc/

  mongodb:
    image: mongo:4.4
    container_name: codelab-mongo
    restart: always
    volumes:
      - ./mongo/data:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth

  neo4j:
    image: neo4j:4.1.3
    container_name: codelab-neo4j
    restart: always
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/plugins:/plugins
      - ./neo4j/import:/import
    ports:
      - 7687:7687
    command: neo4j

  # verdaccio:
  #   image: verdaccio/verdaccio:4
  #   container_name: verdaccio-docker-local-storage-vol
  #   ports:
  #     - 4873:4873
  #   volumes:
  #     # This is bind mounted
  #     - ./storage:/verdaccio/storage
  #     - ./conf:/verdaccio/conf

# volumes:
  # https://docs.docker.com/compose/compose-file/#volume-configuration-reference
  # codelab-volume:
  #   external:
  #     name: codelab-volume
  # verdaccio:
  #   driver: local
