version: '3.6'
services:
  postgres:
    image: postgres:12
    container_name: codelab-external-postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      # - HOST:CONTAINER
      # Allow local machine access
      - 5433:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  graphql-engine:
    image: hasura/graphql-engine:v1.3.2
    container_name: codelab-external-hasura
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: always

    env_file:
      - .env
    environment:
      - HASURA_GRAPHQL_ENABLE_CONSOLE
      - HASURA_GRAPHQL_DEV_MODE
      - HASURA_GRAPHQL_ENABLED_LOG_TYPES
      - HASURA_GRAPHQL_ADMIN_SECRET

volumes:
  db_data:
    name: codelab-postgres-volume
