version: 3
# https://stackoverflow.com/questions/59791091/hasura-endpoint-as-environment-variable
# endpoint: ${CODELAB_HASURA_ENDPOINT}
# endpoint: https://codelab-ai.hasura.app/
endpoint: http://127.0.0.1:8080/
admin_secret: ${HASURA_GRAPHQL_ADMIN_SECRET}
api_paths:
  v1_query: v1/query
  v2_query: v2/query
  v1_metadata: v1/metadata
  graphql: v1/graphql
  config: v1alpha1/config
  pg_dump: v1alpha1/pg_dump
  version: v1/version
metadata_directory: metadata
migrations_directory: migrations
seeds_directory: seeds
actions:
  kind: synchronous
  handler_webhook_baseurl: http://127.0.0.1:3000
  codegen:
    framework: ''
    output_dir: ''
